# Generated by Django 3.1.2 on 2024-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historic_Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_date', models.DateTimeField(blank=True, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(blank=True, max_length=255, null=True)),
                ('cost_per_liter', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
