# Generated by Django 3.1.2 on 2021-10-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_vehicle_ordered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='order',
            field=models.BooleanField(default=False),
        ),
    ]
