# Generated by Django 3.1.2 on 2021-10-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_vehicle_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
