# Generated by Django 3.1.2 on 2021-10-06 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_parts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='date_delivered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parts',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
