# Generated by Django 3.1.2 on 2021-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20211006_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='fitted',
            field=models.BooleanField(default=False),
        ),
    ]
