# Generated by Django 3.1.2 on 2024-03-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_parts_date_fitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
