# Generated by Django 3.1.2 on 2024-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_parts_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='date_fitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='delivered',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='parts',
            name='fitted',
            field=models.CharField(choices=[('Fitted', 'Fitted'), ('Not Fitted', 'Not Fitted')], max_length=100),
        ),
    ]
