# Generated by Django 3.1.2 on 2024-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20240307_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tire_serial_number', models.IntegerField()),
                ('tire_details', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tire_Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='title',
            new_name='part_name',
        ),
    ]
