# Generated by Django 3.1.2 on 2024-03-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
        ('parts', '0011_auto_20240307_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='Vehicle',
        ),
        migrations.AddField(
            model_name='parts',
            name='registration_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle_register'),
        ),
    ]
