# Generated by Django 3.1.2 on 2024-03-18 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0012_auto_20240308_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreIssuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(editable=False, max_length=255, unique=True)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_issues', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle_register')),
            ],
        ),
    ]
