# Generated by Django 3.1.2 on 2024-03-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
        ('parts', '0013_tyreissuance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyreissuance',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.userunit'),
        ),
    ]
