# Generated by Django 3.1.2 on 2024-03-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_auto_20240318_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreissuance',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
