# Generated by Django 3.1.2 on 2024-03-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
        ('parts', '0015_tyreissuance_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGarage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tyreissuance',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_receiver', to='transport.driver'),
        ),
        migrations.CreateModel(
            name='VehicleDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_garage', models.CharField(choices=[('Local', 'Local'), ('External', 'External')], max_length=100)),
                ('garage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.autogarage')),
                ('registration_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle_issues')),
            ],
        ),
    ]
