# Generated by Django 3.1.2 on 2024-03-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
        ('parts', '0016_auto_20240331_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledispatch',
            name='registration_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle_register'),
        ),
    ]
