# Generated by Django 3.1.2 on 2024-03-31 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0017_auto_20240331_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassessment',
            name='date_approved',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicleassessment',
            name='date_verified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicleassessment',
            name='registration_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='transport.vehicle_register'),
        ),
        migrations.AddField(
            model_name='vehicleassessment',
            name='repairs_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='vehicleassessment',
            name='repairs_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassessment',
            name='repairs_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='vehicleassessment',
            name='repairs_verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repairs_verifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassessment',
            name='works_done',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vehicleassessment',
            name='works_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vehicledispatch',
            name='date_dispatched',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicledispatch',
            name='date_vehicle_received',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicledispatch',
            name='garage_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_name', to='parts.autogarage'),
        ),
        migrations.AlterField(
            model_name='vehicledispatch',
            name='registration_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='transport.vehicle_register'),
        ),
    ]
