# Generated by Django 3.1.2 on 2024-04-03 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0018_auto_20240331_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprestPartsAquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_category', models.CharField(choices=[('Electrical', 'Electrical'), ('Suspension', 'Suspension'), ('Transmission', 'Transmission'), ('Tyre', 'Tyre'), ('Windscreen', 'Windscreen'), ('Service part', 'Service part')], max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('part_cost', models.FloatField(null=True)),
                ('date_requested', models.DateField(auto_now=True)),
                ('approve_requisition', models.BooleanField(default=False)),
                ('date_approved', models.DateField()),
                ('registration_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partsimprest', to='transport.vehicle_register')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userimprest', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationimprest', to='transport.station')),
            ],
        ),
    ]
