# Generated by Django 3.1.2 on 2024-04-03 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0019_imprestpartsaquisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestpartsaquisition',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approverimprest', to=settings.AUTH_USER_MODEL),
        ),
    ]
