# Generated by Django 3.1.2 on 2024-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_imprestpartsaquisition_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestpartsaquisition',
            name='invoice',
            field=models.FileField(null=True, upload_to='imprest/invoices/'),
        ),
        migrations.AddField(
            model_name='imprestpartsaquisition',
            name='invoice_no',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='imprestpartsaquisition',
            name='vendor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
