# Generated by Django 3.1.2 on 2024-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_auto_20240403_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestpartsaquisition',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
