# Generated by Django 3.1.2 on 2024-04-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_auto_20240403_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='date_fitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
