# Generated by Django 3.1.2 on 2024-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_auto_20240414_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
