# Generated by Django 3.1.2 on 2024-04-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0024_auto_20240414_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreissuance',
            name='make',
            field=models.CharField(choices=[('Mitchellin', 'Mitchellin'), ('Goodyear', 'Goodyear'), ('Yana', 'Yana'), ('Pirelli', 'Pirelli')], max_length=100, null=True),
        ),
    ]
