# Generated by Django 3.1.2 on 2024-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0025_tyreissuance_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledispatch',
            name='authorization_memo',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='vehicledispatch',
            name='service_invoice',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
