# Generated by Django 3.1.2 on 2024-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0026_auto_20240414_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestpartsaquisition',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
