# Generated by Django 3.1.2 on 2024-04-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0027_imprestpartsaquisition_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestpartsaquisition',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imprestpartsaquisition',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
