# Generated by Django 3.1.2 on 2024-04-14 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0029_auto_20240414_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledispatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatchuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
