# Generated by Django 3.1.2 on 2024-04-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0030_vehicledispatch_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledispatch',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatchuserupdate', to=settings.AUTH_USER_MODEL),
        ),
    ]
