# Generated by Django 3.1.2 on 2024-04-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0031_vehicledispatch_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledispatch',
            name='garage_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garage_name', to='parts.autogarage'),
        ),
    ]
