# Generated by Django 3.1.2 on 2021-09-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_register',
            name='body_type',
            field=models.CharField(choices=[('Double Cab', 'Double Cab'), ('Tipper', 'Tipper'), ('Tanker', 'Tanker'), ('Low Loader', 'Low Loader'), ('Saloon', 'Saloon'), ('Excavator', 'Excavator'), ('SUV', 'SUV'), ('motor Bike', 'Motor Bike')], max_length=100),
        ),
    ]
