# Generated by Django 3.1.2 on 2021-09-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20210914_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_issues',
            old_name='service_description',
            new_name='works_description',
        ),
    ]
