# Generated by Django 3.1.2 on 2021-09-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20210914_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_issues',
            old_name='repair_total',
            new_name='works_total',
        ),
        migrations.AddField(
            model_name='vehicle_issues',
            name='approve_works',
            field=models.BooleanField(default=False),
        ),
    ]
