# Generated by Django 3.1.2 on 2021-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20210914_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_update',
            name='check_report',
            field=models.BooleanField(default=False),
        ),
    ]
