# Generated by Django 3.1.2 on 2021-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_fuel_mgt_update_check_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_mgt_update',
            name='check_report',
        ),
        migrations.AddField(
            model_name='vehicle_issues',
            name='check_report',
            field=models.BooleanField(default=False),
        ),
    ]
