# Generated by Django 3.1.2 on 2021-10-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20211005_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt',
            name='liters_served',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
