# Generated by Django 3.1.2 on 2021-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20211005_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_issues',
            name='parts_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
