# Generated by Django 3.1.2 on 2021-10-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_vehicle_issues_parts_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='job_title',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Plant operator', 'Plant operator')], max_length=100, null=True),
        ),
    ]
