# Generated by Django 3.1.2 on 2021-10-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_driver_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_register',
            name='axles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('White_blue', 'White blue'), ('White_cream', 'White cream'), ('White_green', 'White green'), ('Metallic grey', 'Grey metallic'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Dark steel', 'Dark steel'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Grey blue', 'Grey blue'), ('Gold', 'Gold'), ('Green', 'Green'), ('Grey blue', 'Grey blue')], default='White', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='engine_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='gross_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='load_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='log_book_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='manufacture_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='tare_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='tax_class',
            field=models.CharField(choices=[('Commercial goods', 'Commercial goods'), ('Private', 'Private')], default='not applicable', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle_register',
            name='vehicle_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='make',
            name='vehicle_name',
            field=models.CharField(choices=[('Isuzu', 'Isuzu'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Case', 'Case'), ('Toyota', 'Toyota'), ('Mercedes Benz', 'Mercedes Benz'), ('Man', 'Man'), ('Iveco', 'Iveco'), ('Fiat', 'Fiat'), ('Iveco', 'Iveco'), ('JCB', 'New JCB')], default='Isuzu', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle_register',
            name='body_type',
            field=models.CharField(choices=[('Double Cab', 'Double Cab'), ('Tipper', 'Tipper'), ('Tanker', 'Tanker'), ('Low Loader', 'Low Loader'), ('Saloon', 'Saloon'), ('Excavator', 'Excavator'), ('SUV', 'SUV'), ('motor Bike', 'Motor Bike'), ('Pick up', 'Pickup'), ('Lorry', 'Lorry'), ('Backhoe Loader', 'Backhoe loader'), ('Station Wagon', 'Station wagon'), ('Van', 'Van'), ('Special Purpose', 'Special purpose'), ('Prime Mover', 'Prime mover'), ('Tractor', 'Tractor'), ('L_Sided', 'L_sided')], max_length=100),
        ),
    ]
