# Generated by Django 3.1.2 on 2021-10-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_vehicle_register_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_register',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.fuel_name'),
        ),
    ]
