# Generated by Django 3.1.2 on 2021-10-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_vehicle_register_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='vehicle_name',
            field=models.CharField(choices=[('Isuzu', 'Isuzu'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Case', 'Case'), ('Toyota', 'Toyota'), ('Mercedes Benz', 'Mercedes Benz'), ('Man', 'Man'), ('Iveco', 'Iveco'), ('Fiat', 'Fiat'), ('Iveco', 'Iveco'), ('JCB', 'New JCB')], default='Isuzu', max_length=200, unique=True),
        ),
    ]
