# Generated by Django 3.1.2 on 2022-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_motor_cycle_make_motor_cycle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_cycle_model',
            name='Motor_cycle_model',
            field=models.CharField(choices=[('dt125', 'dt125'), ('tf125', 'tf125')], default='dt125', max_length=200),
        ),
    ]
