# Generated by Django 3.1.2 on 2022-03-22 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0019_auto_20220322_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('pf_no', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('assigned_motorcycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.motor_cycle_model')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.station')),
            ],
        ),
    ]
