# Generated by Django 3.1.2 on 2022-03-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='gender',
        ),
    ]
