# Generated by Django 3.1.2 on 2022-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_generator_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_update',
            name='current_mileage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
