# Generated by Django 3.1.2 on 2022-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0024_auto_20220728_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt',
            name='current_mileage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
