# Generated by Django 3.1.2 on 2022-08-27 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0026_auto_20220728_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fuel_mgt',
            name='previous_mileage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Vendor_station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.fuel_station')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_price', models.FloatField(blank=True, null=True)),
                ('fuel_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.fuel_name')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_fuel_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=100, null=True)),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_mgt_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reference', models.UUIDField(default=uuid.uuid4)),
                ('fuel_amount_requested', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(auto_now=True, null=True)),
                ('fuel_issue_complete', models.BooleanField(default=False)),
                ('date_closed', models.DateTimeField(default=django.utils.timezone.now)),
                ('declined', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('liters_served', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('date_fueled', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fprice', models.CharField(max_length=100, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fapprover1', to=settings.AUTH_USER_MODEL)),
                ('attended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fattendant', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ffueler1', to=settings.AUTH_USER_MODEL)),
                ('driver_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.driver')),
                ('fuel_station_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.fuel_station')),
                ('fuel_type_requested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fueltype', to='transport.vendor_fuel_types')),
                ('price_per_liter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuelprice', to='transport.vendor_price')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.station')),
                ('region_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frcode', to='transport.userunit')),
                ('registration_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.vehicle_register')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequester1', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vendor')),
                ('vendor_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vendor_station')),
            ],
        ),
    ]
