# Generated by Django 3.1.2 on 2022-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_auto_20220827_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_price',
            name='fuel_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
