# Generated by Django 3.1.2 on 2022-08-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0030_auto_20220827_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_fuel_types',
            name='fuel_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_price',
            name='fuel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vendor_fuel_types'),
        ),
    ]
