# Generated by Django 3.1.2 on 2022-09-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0033_auto_20220827_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_m',
            name='price_per_liter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuelprice', to='transport.vendor_price'),
        ),
    ]
