# Generated by Django 3.1.2 on 2022-09-04 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0035_auto_20220904_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_mgt',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='fuel_mgt',
            name='vendor_location',
        ),
        migrations.RemoveField(
            model_name='fuel_mgt_m',
            name='current_mileage',
        ),
        migrations.RemoveField(
            model_name='fuel_mgt_m',
            name='distance_covered',
        ),
        migrations.RemoveField(
            model_name='fuel_mgt_m',
            name='previous_liters_served',
        ),
        migrations.RemoveField(
            model_name='fuel_mgt_m',
            name='previous_mileage',
        ),
        migrations.RemoveField(
            model_name='fuel_mgt_m',
            name='station_mileage',
        ),
        migrations.AlterField(
            model_name='fuel_mgt',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuel_mgt',
            name='attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuel_mgt',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fueler1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuel_mgt',
            name='fuel_type_requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.fuel_name'),
        ),
        migrations.AlterField(
            model_name='fuel_mgt',
            name='price_per_liter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.fuel_price'),
        ),
        migrations.AlterField(
            model_name='fuel_mgt',
            name='region_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcode', to='transport.userunit'),
        ),
        migrations.AlterField(
            model_name='fuel_mgt',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_m',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fapprover1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_m',
            name='attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fattendant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_m',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ffueler1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_m',
            name='region_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frcode', to='transport.userunit'),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_m',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequester1', to=settings.AUTH_USER_MODEL),
        ),
    ]
