# Generated by Django 3.1.2 on 2022-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0037_fuel_mgt_xn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_price',
            name='fuel_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
