# Generated by Django 3.1.2 on 2022-09-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0038_auto_20220909_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_price',
            name='fuel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vendor_fuel_types'),
        ),
    ]
