# Generated by Django 3.1.2 on 2022-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0039_auto_20220909_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
