# Generated by Django 3.1.2 on 2022-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0040_generator_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='liters_served',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
