# Generated by Django 3.1.2 on 2022-09-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0041_auto_20220915_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='price_per_liter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xnfuelprice', to='transport.vendor_price'),
        ),
    ]
