# Generated by Django 3.1.2 on 2022-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0042_auto_20220915_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='location',
            field=models.CharField(choices=[('Headquarters', 'Headquarters'), ('Eastern Region', 'Eastern Region'), ('Central Region', 'Central Region'), ('Northern Region', 'Northern Region'), ('North Eastern', 'North Eastern'), ('Southern Region', 'Southern Region'), ('Western Region', 'Western Region'), ('Informal Settlements Region', 'Informal Settlements Region'), ('Ruai', 'Ruiru Dam'), ('Gigiri', 'Gigiri'), ('Kabete Laboratory', 'Kabete Laboratory'), ('Ruiru Dam', 'Ruiru Dam'), ('Ngethu Treatment Works', 'Ngethu Treatment Works'), ('Thika Dam', 'Thika Dam'), ('Sasumua Treatment Works', 'Sasumua Treatment Works'), ('Kariobangi Treatment Works', 'Kariobangi Treatment Works')], default='Headquarters', max_length=200),
        ),
    ]
