# Generated by Django 3.1.2 on 2022-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0043_auto_20220916_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_price',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
