# Generated by Django 3.1.2 on 2022-09-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0044_vendor_price_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_m',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountprice', to='transport.vendor_price'),
        ),
    ]
