# Generated by Django 3.1.2 on 2022-09-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0046_auto_20220920_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_price',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountprice', to='transport.fuel_price'),
        ),
    ]
