# Generated by Django 3.1.2 on 2022-09-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0047_auto_20220920_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountprice', to='transport.vendor_price'),
        ),
    ]
