# Generated by Django 3.1.2 on 2022-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0048_auto_20220920_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='fuel_issue_complete',
            field=models.BooleanField(default=True),
        ),
    ]
