# Generated by Django 3.1.2 on 2022-11-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0050_auto_20221007_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parts_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('engine', 'engine'), ('suspension', 'suspension'), ('body', 'body'), ('head_lights', 'head_lights'), ('side_lights', 'side_lights'), ('electrical', 'electrical'), ('bushing', 'bushing'), ('mirrors_external', 'mirrors_external'), ('mirrors_internal', 'mirrors_internal'), ('screen', 'screen'), ('brakes', 'brakes'), ('Tyres', 'Tyres'), ('Tubing', 'Tubing'), ('seat', 'seat'), ('wiper_arms', 'wiper_arms'), ('wiper_blades', 'wiper_blades')], default=None, max_length=200)),
                ('serial_number', models.CharField(max_length=100, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.parts_stock')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_reference', models.UUIDField(default=uuid.uuid4)),
                ('Vehicle_issue_topic', models.CharField(max_length=100, null=True)),
                ('vehicle_issue', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_in', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('reason_for_decline', models.TextField(blank=True, null=True)),
                ('current_mileage', models.CharField(max_length=100, null=True)),
                ('next_service', models.CharField(max_length=100, null=True)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.BooleanField(default=False)),
                ('works_description', models.TextField(blank=True, null=True)),
                ('service_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('repair', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('parts_requisition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parts_received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('further_works_required_remarks', models.TextField(blank=True, null=True)),
                ('vehicle_out', models.BooleanField(default=False)),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('down_time', models.CharField(max_length=100, null=True)),
                ('mechanic_assesment', models.TextField(blank=True, null=True)),
                ('approve_works', models.BooleanField(default=False)),
                ('check_report', models.BooleanField(default=False)),
                ('parts_required', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.driver')),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.make')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.model')),
                ('parts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.parts_stock')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.station')),
                ('transport_assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tra', to=settings.AUTH_USER_MODEL)),
                ('transport_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tro', to=settings.AUTH_USER_MODEL)),
                ('transport_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trs', to=settings.AUTH_USER_MODEL)),
                ('vehicle_registration_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle_register')),
            ],
        ),
    ]
