# Generated by Django 3.1.2 on 2023-03-03 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0052_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='assign_request',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
