# Generated by Django 3.1.2 on 2023-03-23 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0054_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='BPO_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='approved_by_BPO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='date_BPO_approved',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='work_ticket_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
