# Generated by Django 3.1.2 on 2023-04-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0055_auto_20230323_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='fuel_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
