# Generated by Django 3.1.2 on 2023-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0056_fuel_mgt_xn_fuel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='fuel_Img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
