# Generated by Django 3.1.2 on 2023-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0057_auto_20230408_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='fuel_Img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='fuelpics/'),
        ),
    ]
