# Generated by Django 3.1.2 on 2023-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0058_auto_20230411_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='fuel_Img',
            field=models.ImageField(blank=True, null=True, upload_to='fuelpics/'),
        ),
    ]
