# Generated by Django 3.1.2 on 2023-05-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0061_motor_bike_make_motor_bike_model_motor_bike_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_bike_model',
            name='motor_cycle_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.motor_bike_make'),
        ),
    ]
