# Generated by Django 3.1.2 on 2023-05-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0062_auto_20230516_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor_bike_register',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.motor_bike_make'),
        ),
        migrations.AddField(
            model_name='motor_bike_register',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.motor_bike_model'),
        ),
    ]
