# Generated by Django 3.1.2 on 2023-05-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0063_auto_20230518_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motor_bike_model',
            old_name='Motor_cycle_model',
            new_name='motor_cycle_model',
        ),
    ]
