# Generated by Django 3.1.2 on 2023-05-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0064_auto_20230522_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor_bike_riders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motor_bike_assignment_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_cycle_reg_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.motor_bike_register')),
                ('rider_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.motor_bike_riders')),
            ],
        ),
    ]
