# Generated by Django 3.1.2 on 2023-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0066_motor_bike_riders_pf_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor_bike_riders',
            name='pf_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
