# Generated by Django 3.1.2 on 2023-05-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0067_auto_20230524_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor_bike_riders',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.station'),
        ),
        migrations.AlterField(
            model_name='motor_bike_assignment_register',
            name='motor_cycle_reg_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.motor_bike_register', unique=True),
        ),
    ]
