# Generated by Django 3.1.2 on 2023-12-26 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0071_fuel_mgt_mb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor_cycle_issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_reference', models.UUIDField(default=uuid.uuid4)),
                ('motor_cycle_topic', models.CharField(max_length=100, null=True)),
                ('motor_cycle_issue', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('motor_cycle_in', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('reason_for_decline', models.TextField(blank=True, null=True)),
                ('current_mileage', models.CharField(max_length=100, null=True)),
                ('next_service', models.CharField(max_length=100, null=True)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.BooleanField(default=False)),
                ('works_description', models.TextField(blank=True, null=True)),
                ('service_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('repair', models.BooleanField(default=False)),
                ('repair_description', models.TextField(blank=True, null=True)),
                ('works_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('parts_requisition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parts_received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('further_works_required_remarks', models.TextField(blank=True, null=True)),
                ('vehicle_out', models.BooleanField(default=False)),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('down_time', models.CharField(max_length=100, null=True)),
                ('mechanic_assesment', models.TextField(blank=True, null=True)),
                ('approve_works', models.BooleanField(default=False)),
                ('check_report', models.BooleanField(default=False)),
                ('parts_required', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('motor_cycle_registration_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.motor_bike_register')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.station')),
                ('rider_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.motor_bike_riders')),
                ('transport_assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transport_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transport_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
