# Generated by Django 3.1.2 on 2024-01-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0072_motor_cycle_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='date_approved',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='date_requested',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
