# Generated by Django 3.1.2 on 2024-01-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0073_auto_20240107_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='date_approved',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
