# Generated by Django 3.1.2 on 2024-01-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0074_auto_20240107_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_mgt_xn',
            name='assign_request',
        ),
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='assign_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
