# Generated by Django 3.1.2 on 2024-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0075_auto_20240128_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('HR-APPROVED', 'HR-APPROVED'), ('BPO-APPROVED', 'BPO-APPROVED'), ('FUELED', 'FUELED')], default='NEW', max_length=50, null=True),
        ),
    ]
