# Generated by Django 3.1.2 on 2024-02-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0077_auto_20240131_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='average_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='fuel_consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='distance_covered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
