# Generated by Django 3.1.2 on 2024-04-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='engine_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='previous_worksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/worksheets'),
        ),
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='site_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/siteimages'),
        ),
    ]
