# Generated by Django 3.1.2 on 2024-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0079_auto_20240406_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_register',
            name='type',
            field=models.CharField(choices=[('Tanker', 'Tanker'), ('Excavator', 'Excavator'), ('Exhauster', 'Exhauster'), ('Flushing unit', 'Flushing Unit')], max_length=100, null=True),
        ),
    ]
