# Generated by Django 3.1.2 on 2024-04-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0080_auto_20240407_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='bulk_fuel_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='category',
            field=models.CharField(choices=[('BULK_FUEL', 'Bulk Fuel'), ('MOTOR_VEHICLE', 'Motor Vehicle')], default='Motor Vehicle', max_length=50, null=True),
        ),
    ]
