# Generated by Django 3.1.2 on 2024-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0083_auto_20240407_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='category',
            field=models.CharField(choices=[('BULK_FUEL', 'Bulk Fuel'), ('MOTOR_VEHICLE', 'Motor Vehicle')], max_length=50, null=True),
        ),
    ]
