# Generated by Django 3.1.2 on 2024-04-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0084_auto_20240407_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_mgt_xn',
            name='previous_bulk_fuel_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
