# Generated by Django 3.1.2 on 2024-04-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0085_fuel_mgt_xn_previous_bulk_fuel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='registration_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.vehicle_register'),
        ),
    ]
