# Generated by Django 3.1.2 on 2024-04-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0086_auto_20240407_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_mgt_xn',
            name='driver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.driver'),
        ),
    ]
