# Generated by Django 3.1.2 on 2024-04-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0092_auto_20240408_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk_Fuel_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reference', models.UUIDField(default=uuid.uuid4)),
                ('fuel_amount_requested', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_plant_hours', models.CharField(max_length=100)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('BPO_approval', models.BooleanField(default=False)),
                ('date_BPO_approved', models.DateTimeField(auto_now=True, null=True)),
                ('date_approved', models.DateTimeField(auto_now=True, null=True)),
                ('fuel_issue_complete', models.BooleanField(default=False)),
                ('date_closed', models.DateTimeField(default=django.utils.timezone.now)),
                ('declined', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('previous_liters_served', models.CharField(max_length=100, null=True)),
                ('liters_served', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('date_fueled', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fprice', models.CharField(max_length=100, null=True)),
                ('accompanying_driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.driver')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by_BPO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assign_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('carrier_registration_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.vehicle_register')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulkdiscountprice', to='transport.vendor_price')),
                ('fuel_station_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.fuel_station')),
                ('fuel_type_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulkfueltype', to='transport.vendor_fuel_types')),
                ('price_per_liter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulkfuelprice', to='transport.vendor_price')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.station')),
                ('region_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.userunit')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vendor')),
                ('vendor_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.vendor_station')),
            ],
        ),
    ]
