# Generated by Django 3.1.2 on 2024-04-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0093_bulk_fuel_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulk_fuel_request',
            old_name='accompanying_driver_name',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='bulk_fuel_request',
            old_name='carrier_registration_no',
            new_name='registration_no',
        ),
    ]
