# Generated by Django 3.1.2 on 2024-04-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0095_auto_20240408_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generator',
            old_name='size',
            new_name='fuel_capacity',
        ),
    ]
