# Generated by Django 3.1.2 on 2023-12-27 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0072_motor_cycle_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(choices=[('Isuzu', 'Isuzu'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Case', 'Case'), ('Toyota', 'Toyota'), ('Mercedes Benz', 'Mercedes Benz'), ('Man', 'Man'), ('Iveco', 'Iveco'), ('Fiat', 'Fiat'), ('Iveco', 'Iveco'), ('JCB', 'New JCB')], default='Isuzu', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=200, null=True)),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiclemgt.make')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('engine_capacity', models.CharField(max_length=100)),
                ('drive_type', models.CharField(choices=[('Rear Wheel Drive', 'Rear Wheel Drive'), ('Four Wheel Drive', 'Four Wheel Drive')], default='Rear Wheel Drive', max_length=100)),
                ('transmission', models.CharField(choices=[('Manual Transmission', 'Manual Transmission'), ('Automatic Transmission', 'Automatical Transmission')], default='Manual Transmission', max_length=200)),
                ('body_type', models.CharField(choices=[('Double Cab', 'Double Cab'), ('Tipper', 'Tipper'), ('Tanker', 'Tanker'), ('Low Loader', 'Low Loader'), ('Saloon', 'Saloon'), ('Excavator', 'Excavator'), ('SUV', 'SUV'), ('motor Bike', 'Motor Bike'), ('Pick up', 'Pickup'), ('Lorry', 'Lorry'), ('Backhoe Loader', 'Backhoe loader'), ('Station Wagon', 'Station wagon'), ('Van', 'Van'), ('Special Purpose', 'Special purpose'), ('Prime Mover', 'Prime mover'), ('Tractor', 'Tractor'), ('L_Sided', 'L_sided')], max_length=100)),
                ('fuel_tank_capacity', models.CharField(max_length=100)),
                ('operational_status', models.CharField(choices=[('operational', 'Operational'), ('grounded', 'Grounded'), ('not applicable', 'Not Applicable')], default='not applicable', max_length=200)),
                ('mechanical_status', models.CharField(choices=[('accident', 'Accident'), ('write off', 'Accident(Write off)'), ('servicable', 'Servicable'), ('insurance', 'Insurance'), ('reparable', 'Reparable'), ('not reparable', 'Not Reparable'), ('Repairs in progress', 'Repairs in progress'), ('not applicable', 'Not Applicable')], default='accident', max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_book', models.FileField(null=True, upload_to='documents/')),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('manufacture_year', models.DateField(blank=True, null=True)),
                ('engine_no', models.CharField(max_length=100, null=True, unique=True)),
                ('color', models.CharField(choices=[('White', 'White'), ('White_blue', 'White blue'), ('White_cream', 'White cream'), ('White_green', 'White green'), ('Metallic grey', 'Grey metallic'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Dark steel', 'Dark steel'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Grey blue', 'Grey blue'), ('Gold', 'Gold'), ('Green', 'Green'), ('Grey blue', 'Grey blue')], default='White', max_length=50)),
                ('vehicle_registration_date', models.DateField(blank=True, null=True)),
                ('gross_weight', models.IntegerField(blank=True, null=True)),
                ('tare_weight', models.IntegerField(blank=True, null=True)),
                ('passengers', models.IntegerField(blank=True, null=True)),
                ('tax_class', models.CharField(choices=[('Commercial goods', 'Commercial goods'), ('Private', 'Private')], default='not applicable', max_length=50)),
                ('axles', models.IntegerField(blank=True, null=True)),
                ('load_capacity', models.IntegerField(blank=True, null=True)),
                ('log_book_number', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.fuel_name')),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiclemgt.make')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiclemgt.model')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.station')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
