# Generated by Django 3.1.2 on 2021-08-23 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210823_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 8, 23, 13, 9, 16, 534355, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
