# Generated by Django 3.1.2 on 2024-03-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_Compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Speed_Governor_Compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NTSACompliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Inspection Date')),
                ('next_inspection_date', models.DateField(verbose_name='Next Inspection Date')),
                ('last_inspection_date', models.DateField(verbose_name='Last Inspection Date')),
                ('inspection_sticker_issued_date', models.DateField(verbose_name='Sticker Issuance Date')),
                ('inspection_sticker_expiry_date', models.DateField(verbose_name='Sticker Expiry Date')),
                ('booking_fee', models.FloatField(verbose_name='Booking Fee')),
                ('inspection_fee', models.FloatField(verbose_name='Inspection Fee')),
                ('registration_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle_register', verbose_name='Vehicle Registration Number')),
            ],
        ),
    ]
