# Generated by Django 3.1.2 on 2024-03-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insurance_Compliance',
            new_name='InsuranceCompliance',
        ),
        migrations.RenameModel(
            old_name='Speed_Governor_Compliance',
            new_name='SpeedGovernorCompliance',
        ),
    ]
