# Generated by Django 3.1.2 on 2024-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_auto_20240320_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntsacompliance',
            name='total_fees',
            field=models.FloatField(null=True, verbose_name='Total Fees'),
        ),
    ]
