# Generated by Django 3.1.2 on 2024-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_ntsacompliance_total_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntsacompliance',
            name='last_inspection_date',
            field=models.DateField(auto_now=True, verbose_name='Last Inspection Date'),
        ),
    ]
