# Generated by Django 3.1.2 on 2024-03-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0078_auto_20240205_1002'),
        ('compliance', '0004_auto_20240320_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecompliance',
            options={'verbose_name': 'Insurance Compliance', 'verbose_name_plural': 'Insurance Compliances'},
        ),
        migrations.AddField(
            model_name='insurancecompliance',
            name='date_policy_expiry',
            field=models.DateField(null=True, verbose_name='Date Policy Expiry'),
        ),
        migrations.AddField(
            model_name='insurancecompliance',
            name='date_policy_issued',
            field=models.DateField(null=True, verbose_name='Date Policy Issued'),
        ),
        migrations.AddField(
            model_name='insurancecompliance',
            name='insurance_fee',
            field=models.FloatField(null=True, verbose_name='Insurance Fee'),
        ),
        migrations.AddField(
            model_name='insurancecompliance',
            name='insurance_provider',
            field=models.CharField(max_length=255, null=True, verbose_name='Insurance Provider'),
        ),
        migrations.AddField(
            model_name='insurancecompliance',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle_register', verbose_name='Vehicle'),
        ),
    ]
